<?php

namespace App\Services;

use DOMDocument;
use DOMElement;
use DOMNode;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

/**
 * Decode editor payloads and keep only the markup needed by a question.
 *
 * CKEditor content is rendered as HTML in several student-facing views, so
 * this boundary must be enforced for every create/update path.
 */
class SanitizedHtml
{
    private const PREFIX = 'b64:';

    private const ALLOWED_TAGS = [
        'a', 'b', 'blockquote', 'br', 'caption', 'code', 'col', 'colgroup',
        'div', 'em', 'figcaption', 'figure', 'h1', 'h2', 'h3', 'h4', 'h5',
        'h6', 'hr', 'i', 'img', 'li', 'ol', 'p', 'pre', 's', 'span', 'strong',
        'sub', 'sup', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr',
        'u', 'ul',
        // MathML generated by the Word importer and accepted by CKEditor.
        'annotation', 'maction', 'maligngroup', 'malignmark', 'math', 'menclose',
        'mfenced', 'mfrac', 'mglyph', 'mi', 'mlabeledtr', 'mmultiscripts',
        'mn', 'mo', 'mover', 'mpadded', 'mphantom', 'mprescripts', 'mroot',
        'mrow', 'ms', 'mscarries', 'mscarry', 'msgroup', 'msline', 'mspace',
        'msqrt', 'msrow', 'mstack', 'mstyle', 'msub', 'msup', 'msubsup',
        'mtable', 'mtd', 'mtext', 'mtr', 'munder', 'munderover', 'none',
        'semantics',
    ];

    private const DROP_TAGS = [
        'applet', 'base', 'button', 'embed', 'form', 'iframe', 'input', 'link',
        'meta', 'object', 'script', 'select', 'style', 'textarea', 'video',
    ];

    private const ALLOWED_ATTRIBUTES = [
        'alt', 'class', 'colspan', 'height', 'href', 'mathbackground',
        'mathcolor', 'mathvariant', 'maxsize', 'minsize', 'rowspan', 'src',
        'stretchy', 'style', 'title', 'width', 'xmlns', 'display', 'encoding', 'fence',
        'linethickness', 'lspace', 'movablelimits',
        'rspace', 'separator', 'symmetric', 'accent', 'accentunder', 'bevelled',
        'largeop', 'scriptlevel', 'voffset', 'rowalign', 'columnalign',
        'columnlines', 'rowlines', 'frame', 'framespacing', 'equalrows',
        'equalcolumns', 'side', 'align', 'depth', 'xlink:href',
    ];

    /** Decode and sanitize direct HTML fields before validation runs. */
    public function prepare(Request $request, array $fields): void
    {
        foreach ($fields as $field) {
            if (! $request->exists($field)) {
                continue;
            }

            $value = $request->input($field);

            if ($value !== null && ! is_string($value)) {
                continue;
            }

            $value = $this->decode($value, $field);
            $request->merge([$field => $this->sanitize($value)]);
        }
    }

    /** @throws ValidationException when a browser payload is malformed. */
    private function decode(?string $value, string $field): ?string
    {
        if ($value === null || ! str_starts_with($value, self::PREFIX)) {
            return $value;
        }

        $decoded = base64_decode(substr($value, strlen(self::PREFIX)), true);

        if ($decoded === false || preg_match('//u', $decoded) !== 1) {
            throw ValidationException::withMessages([
                $field => 'Isi editor tidak valid. Silakan muat ulang halaman dan coba lagi.',
            ]);
        }

        return $decoded;
    }

    /**
     * Sanitize an HTML fragment while retaining tables and MathML.
     * Unknown harmless wrappers are unwrapped; active/embed elements vanish.
     */
    public function sanitize(?string $html): ?string
    {
        if ($html === null || trim($html) === '') {
            return $html;
        }

        $dom = new DOMDocument('1.0', 'UTF-8');
        $previous = libxml_use_internal_errors(true);
        $dom->loadHTML(
            '<?xml encoding="UTF-8"?><!DOCTYPE html><html><body>'.$html.'</body></html>',
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_NONET
        );
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        $body = $dom->getElementsByTagName('body')->item(0);

        if (! $body) {
            return '';
        }

        foreach (iterator_to_array($body->childNodes) as $child) {
            $this->sanitizeNode($child);
        }

        $result = '';

        foreach ($body->childNodes as $child) {
            $result .= $dom->saveHTML($child);
        }

        return trim($result);
    }

    private function sanitizeNode(DOMNode $node): void
    {
        if (! $node instanceof DOMElement) {
            return;
        }

        $tag = strtolower($node->localName ?: $node->tagName);

        if (in_array($tag, self::DROP_TAGS, true)) {
            $node->parentNode?->removeChild($node);

            return;
        }

        if (! in_array($tag, self::ALLOWED_TAGS, true)) {
            $parent = $node->parentNode;

            if (! $parent) {
                return;
            }

            while ($node->firstChild) {
                $child = $node->firstChild;
                $parent->insertBefore($child, $node);
                $this->sanitizeNode($child);
            }

            $parent->removeChild($node);

            return;
        }

        foreach (iterator_to_array($node->attributes) as $attribute) {
            $name = strtolower($attribute->name);

            if (! in_array($name, self::ALLOWED_ATTRIBUTES, true)) {
                $node->removeAttributeNode($attribute);

                continue;
            }

            if ($name === 'style') {
                // Inline CSS is not needed to render imported questions and
                // would create another injection surface.
                $node->removeAttributeNode($attribute);

                continue;
            }

            if (in_array($name, ['href', 'src', 'xlink:href'], true)
                && ! $this->isSafeUrl($attribute->value)) {
                $node->removeAttributeNode($attribute);
            }
        }

        foreach (iterator_to_array($node->childNodes) as $child) {
            $this->sanitizeNode($child);
        }
    }

    private function isSafeUrl(string $url): bool
    {
        $url = trim($url);

        if ($url === '' || str_starts_with($url, '#') || str_starts_with($url, '/')) {
            return true;
        }

        if (preg_match('/^data:image\/(?:gif|jpe?g|png|webp);base64,/i', $url) === 1) {
            return true;
        }

        $scheme = strtolower((string) parse_url($url, PHP_URL_SCHEME));

        return in_array($scheme, ['http', 'https'], true);
    }
}
